In [1]:
import pandas as pd

In [3]:
df = pd.read_excel(r"C:\Users\Jatin Code\GENAI\phase-01-python\employees.xlsx")

In [4]:
df.head()

   emp_id   name department       city  salary  experience joining_date
0     101  Jatin         AI      Delhi   75000           2   2024-01-15
1     102  Rahul         HR     Mumbai   50000           3   2023-06-10
2     103   Aman         AI  Bangalore   82000           1   2025-02-01
3     104  Priya      Sales      Delhi   45000           4   2022-09-21
4     105   Neha         HR       Pune   52000           2   2024-03-11

In [15]:
data = {
    "name" : ["Jatin" , "Aryan" , "Rahul"],
    "marks" : [90 , 80 , 95],
    "city" : ["Delhi" , "Mumbai" , "Pune"]
}

In [16]:
df = pd.DataFrame(data)

In [17]:
df

    name  marks    city
0  Jatin     90   Delhi
1  Aryan     80  Mumbai
2  Rahul     95    Pune

In [20]:
df["grade"] = ['A' , 'B' , 'C']

In [21]:
df

    name  marks    city grade
0  Jatin     90   Delhi     A
1  Aryan     80  Mumbai     B
2  Rahul     95    Pune     C

In [22]:
df.describe()

           marks
count   3.000000
mean   88.333333
std     7.637626
min    80.000000
25%    85.000000
50%    90.000000
75%    92.500000
max    95.000000

loc and  iloc

In [23]:
import pandas as pd

data = {
    "name": ["Jatin", "Aryan", "Rahul"],
    "marks": [90, 80, 95],
    "city": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)

print(df)

    name  marks    city
0  Jatin     90   Delhi
1  Aryan     80  Mumbai
2  Rahul     95    Pune

In [24]:
df.iloc[0,1]

90

df.loc[row_label, column_label]

In [25]:
df.loc[0, "name"]

'Jatin'